<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Benday.Demo123.Api\Benday.Demo123.Api.csproj" />
    <ProjectReference Include="..\Benday.Demo123.UnitTests\Benday.Demo123.UnitTests.csproj" />
    <ProjectReference Include="..\..\src\Benday.Demo123.WebUi\Benday.Demo123.WebUi.csproj" />
  </ItemGroup>
</Project>